#!/usr/bin/env python

import os

env = SConscript("../external/godot-cpp/SConstruct")

scons_cache_path = os.environ.get("SCONS_CACHE", os.path.join(os.path.expanduser("~"), ".scons_cache"))
if not os.path.exists(scons_cache_path):
    os.makedirs(scons_cache_path)
CacheDir(scons_cache_path)
Decider("MD5")

env.Append(CPPPATH=["src/", "../external/godot-cpp/include/"])
sources = Glob("src/*.cpp")

env.Append(LIBPATH=["../external/godot-cpp/bin"])

library = env.SharedLibrary(
    "bin/libliquid_glass_extension{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
    LIBS=["libgodot-cpp" + env["suffix"] + env["LIBSUFFIX"]]
)

Default(library)