#!/usr/bin/env python

import os
import sys

# Add game root to path for godot-cpp
sys.path.insert(0, os.path.join(os.getcwd(), "..", ".."))

# Import godot-cpp build configuration
env = SConscript("../../external/godot-cpp/SConstruct")

# Enable cache
scons_cache_path = os.environ.get(
    "SCONS_CACHE", os.path.join(os.path.expanduser("~"), ".scons_cache")
)
if not os.path.exists(scons_cache_path):
    os.makedirs(scons_cache_path)
CacheDir(scons_cache_path)
Decider("MD5")

# Add source directories and godot-cpp include directories
env.Append(CPPPATH=["src/", "../../external/godot-cpp/include/"])
sources = Glob("src/*.cpp")

# Ensure linking to godot-cpp library
env.Append(LIBPATH=["../../external/godot-cpp/bin"])

# Build shared library
library = env.SharedLibrary(
    "bin/libsystem_tray{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
    LIBS=["user32", "shell32", "libgodot-cpp" + env["suffix"] + env["LIBSUFFIX"]],
)

# Set build target
Default(library)
